### ISSUE TITLE
Audio bug on web

### ISSUE THREAD

**Issue by ejb** [edbentley/replay#28]
I intermittently experience this bug on Chrome, even though my game doesn't have any audio.

<img width="678" alt="Screenshot 2020-07-11 at 19 48 30" src="https://user-images.githubusercontent.com/1442752/87235901-a4cfdb00-c3af-11ea-8154-2e8a082cc0aa.png">

**Comment by edbentley** [comment]
I believe this should no longer be a problem since we switched to the web audio API in https://github.com/edbentley/replay/pull/39?

**Comment by ejb** [comment]
Yeah I haven’t encountered it recently so can probably mark as resolved
