### ISSUE TITLE
Expanded audio API

### ISSUE THREAD

**Issue by ejb** [edbentley/replay#36]
Happy to implement the web version of this myself, but wanted to open it up for feedback first.

The proposed additions are:
- getStatus
- getVolume / setVolume
- getDuration

See below for example usage.

```js
// `status` value can be `paused`, `playing` or `ended`
const status = mySound.getStatus();

// volume is a value between 0 (muted) and 1 (max)
const prevVolume = mySound.getVolume();
mySound.setVolume(0.75);

// returns duration of audio in seconds
const duration = mySound.getDuration();
```

**Comment by edbentley** [comment]
Looks good to me.

My only comment is that you can have multiple sounds (of the same file) playing at the same time and currently you can only access the first one. But that can be handled in a later PR.
