### ISSUE TITLE
High DPI screens on web

### ISSUE THREAD

**Issue by ejb** [edbentley/replay#53]
On high DPI screens (sometimes called "retina"), it would be good to scale the canvas by [devicePixelRatio](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio) so that the graphics stay nice and sharp.

**Comment by edbentley** [comment]
I've been thinking about whether [srcset](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/srcset) could be utilised for this, so you can provide multiple resolutions of your image files.

So far I've been including _just_ the highest resolution image I need and it seems ok. So if I have an image texture that is 30x30 in game coordinates, I'll use a 90x90px image file.
