### ISSUE TITLE
Check sprite IDs

### ISSUE THREAD

**Issue by ejb** [edbentley/replay#57]
Replay should throw a helpful error if:
- A sprite is missing the `id` property
- Any sprites share the same `id`

This will help prevent common sprite-based bugs!

**Comment by edbentley** [comment]
> A sprite is missing the id property

Have you tried TypeScript? 😜 

Jokes aside, this would be nice especially on detecting duplicate `id`s. My only concern is it might impact the runtime performance, if it was significant we could just check in development mode.

**Comment by ejb** [comment]
Yeah I spent an hour debugging an issue that simply came down to duplicate ids last night. Even checking in dev mode would have been a huge timesaver!

**Comment by edbentley** [comment]
The duplicate ID problem is fixed. To be honest, I'm not sure about throwing errors on missing props. It's a slippery slope (do we throw if textures are missing props?) which can hurt runtime performance, and there are already ways of getting error messages for this (types 😉 ).

**Comment by ejb** [comment]
Thanks for adding that. For the record I am in favour of as many helpful error messages as possible! Even if they’re only enabled in dev environments for performance reasons. It’s not fair to expect less experienced users, who are more likely to encounter these kinds of bugs, to rely on advanced tools like typescript.
