### ISSUE TITLE
Text styling API proposal

### ISSUE THREAD

**Issue by ejb** [edbentley/replay#65]
The current `text` texture API (below) doesn't allow some fairly basic settings such as font weight, and requires the family and size to be set each time.

```js
t.text({
  text: `foo bar`,
  align: 'start',
  font: {
    size: 20,
    name: 'Barlow Semi Condensed',
  }
});
```

Here's my proposal for a new API which provides more options and switches "name" to the more standard "family". See [this article](http://tutorials.jenkov.com/html5-canvas/text.html#fonts-and-styles) for more details on each property.

I would also suggest that every property is optional; the others will cascade from either Replay's defaults or `gameProps.defaultFont`. 

```js
t.text({
  text: `foo bar`,
  font: {
    size: 20,
    family: 'Barlow Semi Condensed',
    weight: 'bold',
    style: 'italic',
    baseline: 'alphabetic',
    align: 'start',
  }
});
```

(Note: I removed the property `decoration` since it's not supported by HTML canvas, unfortunately.)

**Comment by edbentley** [comment]
Yeah this proposal looks good. The only thing I'm not sure on is whether props like `align` should be within `font` or not.

I'd also like to find a way to add multi-line text, though this can be a separate effort.
