### ISSUE TITLE
replay-core: ts-loader missing from package.json

### ISSUE THREAD

**Issue by ejb** [edbentley/replay#74]
Jotting this down so I don't forget

**Comment by edbentley** [comment]
Did you run `npm install` in the top level and then `npx lerna bootstrap`? I believe with lerna we shouldn't need it (see [here](https://github.com/lerna/lerna/blob/6cb8ab2d4af7ce25c812e8fb05cd04650105705f/README.md#common-devdependencies)) - the only dev dependencies needed are those used on the command line.

**Comment by ejb** [comment]
A fresh clone confirms... you are correct
