### ISSUE TITLE
Spacing issue

### ISSUE THREAD

**Issue by logan-markewich** [edbentley/replay#76]
One small thing I noticed, when tiling a sprite, even though the tiles are spaced apart exactly (as in, the space between each tile is equal to the tile size), there is a small gap when rendering. The only workaround I've found is to make the tiles slightly bigger than the spacing. 

![image](https://user-images.githubusercontent.com/22285038/108582129-cf472680-72f6-11eb-8a11-075cd20e0b54.png)

Inspecting the sprite X,Y locations, everything is a perfect int, so it's not a random float rounding thing.

Seems like a possible bug! Any ideas?

**Comment by ejb** [comment]
Hi there! I’ve encountered the same issue while developing tile-based games too.

It does appear to be a common issue in 2d game development. See [this stackoverflow thread](https://gamedev.stackexchange.com/questions/148247/prevent-tile-layout-gaps), for example.

In my games, I’ve found success by scaling each image texture to _slightly_ larger than needed. For example, [in Playset’s repeating pattern component](https://github.com/ejb/playset/blob/f106f9819b6f22712851748d640425120f463ecc/src/pattern.js#L32), I’m adding an extra 0.1 to the width and height to avoid these hairline cracks.

Hope that helps! Maybe one day there will be a built-in solution to this in replay, though I’m not sure what that would be.

**Comment by logan-markewich** [comment]
Thanks! I'm pretty new to making games, but I'm glad it's a common problem
