### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by edbentley** [edbentley/replay#9]
Add support for deploying to the Android platform, just like we can for iOS.

**Comment by thundercipher** [comment]
Can I try to do this?

**Comment by edbentley** [comment]
@thundercipher Absolutely!

I haven't started on it so you can approach it however you feel best. You can check the Swift package as a reference for how it could work.

If you manage to make some progress on it, I highly recommend creating a WIP pull request as early as possible, to make sure we're aligned on the direction. Feel free to get in touch if you have any questions! :)
